config/routes.rb
Obtuse::Application.routes.draw do
  resources :witticisms
  resources :quotes

  root to: "quotes#index"
end

app/models/witticism.rb
class Witticism < ActiveRecord::Base

  serialize :quote

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    size = rand(4) + 4
    @quote = Markov.new.gimme(size)
    @save_quote = {}
      @quote.each_with_index{|x, idx| @save_quote[idx] = {:text => x.text, :source => x.source, :index => x.index} }
    @previous_source = @quote.first.source
    @previous_index = @quote.first.index
  end

  def show
    @quote = Witticism.find(params[:id]).quote
    @quote = @quote.map{|x| OpenStruct.new(x.last)}
    @previous_source = @quote.first.source
    @previous_index = @quote.first.index

  end


end

app/controllers/witticisms_controller.rb
class WitticismsController < ApplicationController
  before_action :set_witticism, only: [:show, :edit, :update, :destroy]

  # GET /witticisms
  # GET /witticisms.json
  def index
    @witticisms = Witticism.all
  end

  # GET /witticisms/1
  # GET /witticisms/1.json
  def show
  end

  # GET /witticisms/new
  def new
    @witticism = Witticism.new
  end

  # GET /witticisms/1/edit
  def edit
  end

  def random
  end

  # POST /witticisms
  # POST /witticisms.json
  def create
    @witticism = Witticism.new(witticism_params)
    @witticism.quote = params['witticism']['quote']
    respond_to do |format|
      if @witticism.save
        # add chappelle, kaufman, and mitch hedburg
        logger.info((@witticism.id.to_s + " ") * 10)
        format.html { redirect_to @witticism, notice: 'Witticism was successfully created.' }
        format.json { render action: 'show', status: :created, location: @witticism }
      else
        format.html { render action: 'new' }
        format.json { render json: @witticism.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /witticisms/1
  # PATCH/PUT /witticisms/1.json
  def update
    respond_to do |format|
      if @witticism.update(witticism_params)
        format.html { redirect_to @witticism, notice: 'Witticism was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @witticism.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /witticisms/1
  # DELETE /witticisms/1.json
  def destroy
    @witticism.destroy
    respond_to do |format|
      format.html { redirect_to witticisms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_witticism
      @witticism = Witticism.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def witticism_params
      params.require(:witticism).permit(:quote)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def do_break(o)
    !same_source(o) || !successive_index(o)
  end

  def should_close_span(o)
    foo = !same_source(o)
    bar = !successive_index(o)
    tom = foo || bar
    tom
  end

  def in_a_row(o)
    same_source(o) && successive_index(o)
  end

  def successive_index(o)
#    binding.pry
    (@previous_index.succ == o.index)
  end

  def same_source(o)
    (o.source == @previous_source)
  end
end

app/helpers/witticisms_helper.rb
module WitticismsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Obtuse</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
      <style type="text/css">
    /* Apply (proposed) CSS style. Plugin looks for elements with class named "balance-text" */
    .witticism {
        text-wrap: balanced;
    }
    </style>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/quotes/index.html.erb
<div id='hidden-dragon'>
  <%= @quote.map{|x| x.text}.join(" ") %>
</div>


<h1 class="random-quote">

  <% o = @quote.pop %>

  <span class=<%= o.source.to_s %> data-index=<%= o.index %>>
    <%= o.text%>

  <% @quote.each do |o| %>

    <% if should_close_span(o) %>
      </span>
      <span class=<%= o.source.to_s %> data-index=<%= o.index %>>
    <% end %>

    <%= o.text%>

    <%#= o.index %>
    <% @previous_source = o.source %>
    <% @previous_index = o.index %>
  <% end %>
  </span>

</h1>

<ul class="buttons">
  <li><%= link_to "&#x2713;".html_safe, '#', :onclick => 'createWitticism()', :class => "save_button" %></li>
  <li><%= link_to "&rarr;".html_safe, "/" %></li>
</ul>

app/views/quotes/show.html.erb
<h1 class="random-quote">

  <% o = @quote.shift %>

  <span class=<%= o.source.to_s %> data-index=<%= o.index %>>
    <%= o.text%>

  <% @quote.each do |o| %>

    <% if should_close_span(o) %>
      </span>
      <span class=<%= o.source.to_s %> data-index=<%= o.index %>>
    <% end %>

    <%= o.text%>

    <%#= o.index %>
    <% @previous_source = o.source %>
    <% @previous_index = o.index %>
  <% end %>
  </span>

</h1>

app/views/witticisms/_form.html.erb
<%= simple_form_for(@witticism) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :quote %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/witticisms/edit.html.erb
<div class="row">
<h2>Editing witticism</h2>

<%= render 'form' %>

<%= link_to 'Show', @witticism %> |
<%= link_to 'Back', witticisms_path %>
</div>

app/views/witticisms/index.html.erb
<div class="row">

<h2>Listing witticisms</h2>

<table class="witticisms">
  <thead>
    <tr>
      <th>Quote</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @witticisms.each do |witticism| %>
      <tr>
        <td><%= witticism.quote %></td>
        <td><%= link_to 'Show', witticism %></td>
        <td><%= link_to 'Edit', edit_witticism_path(witticism) %></td>
        <td><%= link_to 'Destroy', witticism, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Witticism', new_witticism_path, :class => "button" %>

</div>

app/views/witticisms/new.html.erb
<div class="row">
<h2>New witticism</h2>

<%= render 'form' %>

<%= link_to 'Back', witticisms_path %>
</div>

app/views/witticisms/random.html.erb
<div class="random-witticism"></div>

app/views/witticisms/show.html.erb
<p id="notice"><%= notice %></p>
<div class="witticism-container">
  <h1 class="witticism animated fadeInUp"><%= @witticism.quote %></h1>
</div>
<div class="links">
  <%= link_to raw('&larr;'), witticisms_path %>
  <%= link_to 'Edit', edit_witticism_path(@witticism) %>
</div>